backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_library:
  name: cloudinary
  config:
    clude_name: fmeyer1980
    api_key: 711621795934345
    default_transformations:
      - fetch_format: auto
        quality: auto

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'posts'
    create: true
    publish_mode: editorial_workflow
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
        label: 'Layout',
        name: 'layout',
        widget: 'hidden',
        default: 'layouts/post.njk'
      }
